name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: 'prod'
    steps:
      - uses: actions/checkout@v2

      - name: BuildImage
        run: make buildimage

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUBUSER }}
          password: ${{ secrets.DOCKERHUBPASSWORD }}
        
      - name: Publish
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: zhaoyi0113/rancher-go-api:latest

  
